version: "3"
services:
  web:
    image: nginx:1.15.6
    shm_size: 256m
    ports:
      - "8000:80"
      - "9515:9515"
    depends_on:
      - app
    volumes:
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
  app:
    build: ./docker/php
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: laravel-auth-test
      MYSQL_USER: user
      MYSQL_PASSWORD: P@ssword2022
      MYSQL_ROOT_PASSWORD: P@ssword2022
    ports:
      - "33060:3306"
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
